### PR TITLE
Change app ID (fixes #1 and #4)

### LINKED ISSUE #1: Change app ID?
The current app ID is `org.fairphone.launcher`. Should we change it to `community.fairphone.launcher`?

### LINKED ISSUE #4: Debug builds not working anymore
Since 4396f1890ac5b859880df5658287ff5db8203faf, debug builds fail:
```
/home/pierre/www/FP1-Launcher/app/src/main/res/layout/all_apps_cling.xml:16: AAPT: error: attribute 'org.fairphone.launcher:drawIdentifier' not found.
    
/home/pierre/www/FP1-Launcher/app/src/main/res/layout/apps_customize_pane.xml:57: AAPT: error: attribute 'org.fairphone.launcher:clingFocusedX' not found.
    
/home/pierre/www/FP1-Launcher/app/src/main/res/layout/apps_customize_pane.xml:57: AAPT: error: attribute 'org.fairphone.launcher:clingFocusedY' not found.
    
/home/pierre/www/FP1-Launcher/app/src/main/res/layout/apps_customize_pane.xml:57: AAPT: error: attribute 'org.fairphone.launcher:maxAppCellCountX' not found.
    
/home/pierre/www/FP1-Launcher/app/src/main/res/layout/apps_customize_pane.xml:57: AAPT: error: attribute 'org.fairphone.launcher:maxAppCellCountY' not found.
    
/home/pierre/www/FP1-Launcher/app/src/main/res/layout/apps_customize_pane.xml:57: AAPT: error: attribute 'org.fairphone.launcher:maxGap' not found.
    
/home/pierre/www/FP1-Launcher/app/src/main/res/layout/apps_customize_pane.xml:57: AAPT: error: attribute 'org.fairphone.launcher:pageLayoutHeightGap' not found.
    
/home/pierre/www/FP1-Launcher/app/src/main/res/layout/apps_customize_pane.xml:57: AAPT: error: attribute 'org.fairphone.launcher:pageLayoutPaddingBottom' not found.
    
/home/pierre/www/FP1-Launcher/app/src/main/res/layout/apps_customize_pane.xml:57: AAPT: error: attribute 'org.fairphone.launcher:pageLayoutPaddingLeft' not found.
    
/home/pierre/www/FP1-Launcher/app/src/main/res/layout/apps_customize_pane.xml:57: AAPT: error: attribute 'org.fairphone.launcher:pageLayoutPaddingRight' not found.
    
/home/pierre/www/FP1-Launcher/app/src/main/res/layout/apps_customize_pane.xml:57: AAPT: error: attribute 'org.fairphone.launcher:pageLayoutPaddingTop' not found.
    
/home/pierre/www/FP1-Launcher/app/src/main/res/layout/apps_customize_pane.xml:57: AAPT: error: attribute 'org.fairphone.launcher:pageLayoutWidthGap' not found.
    
/home/pierre/www/FP1-Launcher/app/src/main/res/layout/apps_customize_pane.xml:57: AAPT: error: attribute 'org.fairphone.launcher:widgetCellHeightGap' not found.
    
/home/pierre/www/FP1-Launcher/app/src/main/res/layout/apps_customize_pane.xml:57: AAPT: error: attribute 'org.fairphone.launcher:widgetCellWidthGap' not found.
    
/home/pierre/www/FP1-Launcher/app/src/main/res/layout/apps_customize_pane.xml:57: AAPT: error: attribute 'org.fairphone.launcher:widgetCountX' not found.
    
/home/pierre/www/FP1-Launcher/app/src/main/res/layout/apps_customize_pane.xml:57: AAPT: error: attribute 'org.fairphone.launcher:widgetCountY' not found.
    
/home/pierre/www/FP1-Launcher/app/src/main/res/layout/custom_workspace_cling.xml:17: AAPT: error: attribute 'org.fairphone.launcher:drawIdentifier' not found.
    
/home/pierre/www/FP1-Launcher/app/src/main/res/layout/folder_cling.xml:16: AAPT: error: attribute 'org.fairphone.launcher:drawIdentifier' not found.
    
/home/pierre/www/FP1-Launcher/app/src/main/res/layout/hotseat.xml:16: AAPT: error: attribute 'org.fairphone.launcher:cellCountX' not found.
    
/home/pierre/www/FP1-Launcher/app/src/main/res/layout/hotseat.xml:16: AAPT: error: attribute 'org.fairphone.launcher:cellCountY' not found.
```

### PR DESCRIPTION
**Pull request by Rudloff**
- [x] App ID: `org.fairphone.launcher` &rarr; `community.fairphone.launcher`. Closes #1 
- [x] Increase `versionCode` and bump `versionName` to 2.0
- [x] Directory structure: `org/fairphone/launcher/` &rarr; `community/fairphone/launcher/`
- [x] Remove hardcoded references to res attributes by package name. Closes #4 

Extra:
- [x] Make `gradlew` executable
- [x] Remove residuary `proguard-rules.txt`
- [x] Ignore `app/build/` folder for Git

### CODE REVIEW

**Comment by Rudloff** [comment]
I didn't see #2.
We should wait for it to be merged then rebase this PR.

**Comment by Roboe** [comment]
Thank you for be84525

**Comment by z3ntu** [comment]
Folder structure is still `app/src/main/java/org/fairphone/` instead of `app/src/main/java/community/fairphone/`

**Review by z3ntu — DISMISSED** [review]
Folder structure is still `app/src/main/java/org/fairphone/` instead of `app/src/main/java/community/fairphone/`

**Comment by Roboe** [comment]
Working on it

**Comment by Rudloff** [comment]
@Roboe Do you want me to do it?

**Comment by Roboe** [comment]
No, I'll push it here now

**Review by Roboe — APPROVED** [review]

**Comment by Roboe** [comment]
Anything, @z3ntu?

**Comment by z3ntu** [comment]
grep reveals that there's still `org.fairphone` stuff in there.

**Comment by z3ntu** [comment]
And the build fails horribly...

**Comment by Roboe** [comment]
Fails because of #4. Remove the `debug` flavour from `build.gradle` as a workaround. ~~I'll rebase [fix/failing-debug-builds](https://github.com/WeAreFairphone/FP1-Launcher/tree/fix/failing-debug-builds) after this PR is merged. I will also fix the rest of `org.fairphone` resource stuff there.~~
I'll add patches for #4 here, better. Wait for them, please.

**Comment by Rudloff** [comment]
Release build works for me :+1:

**Comment by z3ntu** [comment]
> grep reveals that there's still `org.fairphone` stuff in there.

**Comment by Roboe** [comment]
Resource stuff related to #4, @z3ntu. Be patient.

**Comment by z3ntu** [comment]
:man_shrugging:

**Comment by Roboe** [comment]
Should be ready now. Please, review it, @z3ntu.

**Comment by Roboe** [comment]
Things here are back to normal now after the anti-spam system blackout. Waiting for your ok to merge this, @z3ntu!

**Review by z3ntu — APPROVED** [review]
Enormous diff, but LGTM

**Pull request merged**
